stages:
    - Prepare test envronment
    - Unit test
    - Functional test
    - Acceptance test
    - Merge and push
    
before_script:
    - docker info

Build test image:
    stage: Prepare test envronment
    script: 
        - docker build -t hello-test --target test .
           
Run unit tests:
    stage: Unit test
    script: 
        - docker run -d --name hello-test --rm hello-test
        - docker exec hello-test ./vendor/bin/codecept run unit --xml --coverage --coverage-html --coverage-xml
        
Run functional tests:
    stage: Functional test
    script: 
        - docker run -d --name hello-test --rm hello-test
        - docker exec hello-test ./vendor/bin/codecept run functional --xml --coverage --coverage-html --coverage-xml
        
Run acceptance tests:
    stage: Acceptance test
    script: 
        - docker run -d --name hello-test --rm hello-test
        - docker exec hello-test ./vendor/bin/codecept run acceptance

Merge and push trunk:
    stage: Merge and push
    except: 
        - trunk
    script: 
        - git fetch
        - git checkout trunk
        - git pull
        - git merge origin/master
        - git merge origin/$CI_COMMIT_REF_NAME
        - git config --global user.name "cirunner"
        - git config --global user.email "gitlab-runner@ntsdev2.sch.gr"
        - git push git@150.140.26.209:Microservices/HelloWorld/HelloService.git HEAD:trunk   