before_script:
  - docker info
  
merge_master:
    except: 
        - master

build_test_image:
    script: 
        - docker build -t hello-test --target test .
        
run_test_image:
        - docker run -d --name hello-test --rm hello-test

execute_tests:
        - docker exec hello-test ./vendor/bin/codecept run --xml --coverage --coverage-html --coverage-xml

after_script:
    - docker stop hello-test