stages:
    - prepare
    - build
    - test
    - push
 
prepare_trunk:
    stage: prepare
    except: 
        - master
    script: 
        - git fetch
        - git checkout trunk
        - git pull
        - git merge origin/master
        - git merge origin/$CI_COMMIT_REF_NAME

build_test_image:
    stage: build
    before_script:
        - docker info
    script: 
        - docker build -t hello-test --target test .
        
run_tests:
    stage: test
    script: 
        - docker run -d --name hello-test --rm hello-test
        - docker exec hello-test ./vendor/bin/codecept run --xml --coverage --coverage-html --coverage-xml
    after_script:
        - docker stop hello-test
        
push_to_trunk:
    stage: push
    except: 
        - master
    script: 
        - git config --global user.name "cirunner"
        - git config --global user.email "gitlab-runner@ntsdev2.sch.gr"
        - git push git@150.140.26.209:Microservices/HelloWorld/HelloService.git HEAD:trunk