image: docker:19.03.12
variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""

before_script:
  - docker info

build_image:
    script: 
        - docker build -t hello-test --target test .
        - docker run --name hello-test --rm hello-test
        - docker exec hello-test ./vendor/bin/codecept run --xml --coverage --coverage-html --coverage-xml
        - docker stop hello-test

        