FROM php:7.4-cli
MAINTAINER ktogias

EXPOSE 80

RUN apt update && apt install zip libzip-dev -y
RUN docker-php-ext-install zip && docker-php-ext-enable zip

WORKDIR /php
        
CMD ["php", "-S", "0.0.0.0:80", "src/hello.php"]