#!/bin/bash

STOP_DEV=false;

if [ "$( docker container inspect -f '{{.State.Status}}' hello-dev )" != "running" ]
then
    echo 'Setting up dev environment...'
    docker build -t hello-dev --target dev .
    docker run -d --volume ./php:/php:Z --name hello-dev --rm hello-dev
    STOP_DEV=true;
fi

echo 'Running unit tests...'
docker exec hello-dev ./vendor/bin/codecept run unit
status=$?
if [ $status -ne 0 ]
then
    echo "Unit tests fail"
    exit $status
fi

echo 'Running functional tests...'
docker exec hello-dev ./vendor/bin/codecept run functional
if [ $status -ne 0 ]
then
    echo "Functional tests fail"
    exit $status
fi

echo 'Running acceptance tests...'
docker exec hello-dev ./vendor/bin/codecept run acceptance
status=$?
if [ $status -eq 0 ]
then
    echo "Success"
else
    echo "Acceptance tests fail"
fi

if $STOP_DEV
then
    docker stop hello-dev
fi

exit $status

